# swagger.yaml
# 这个文件定义了 API 的 OpenAPI 规范，用于生成 Swagger UI 文档。
# 它详细描述了所有的 API 端点、请求/响应格式和认证方式。

openapi: 3.0.0
info:
  title: EasyLogin API
  version: 1.0.0
  description: 带有令牌刷新机制的登录系统 API

servers:
  - url: http://localhost:3000
    description: 开发服务器

paths:
  /auth/register:
    post:
      summary: 注册新用户
      tags:
        - 认证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  description: 用户名
                email:
                  type: string
                  description: 电子邮箱
                password:
                  type: string
                  description: 密码
      responses:
        '201':
          description: 用户注册成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userId:
                    type: integer
        '400':
          description: 验证错误
        '500':
          description: 服务器错误

  /auth/login:
    post:
      summary: 用户登录
      tags:
        - 认证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: 用户名
                password:
                  type: string
                  description: 密码
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: 无效的凭证
        '500':
          description: 服务器错误

  /auth/refresh:
    post:
      summary: 刷新访问令牌
      tags:
        - 认证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  description: 刷新令牌
      responses:
        '200':
          description: 令牌刷新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '403':
          description: 无效的刷新令牌
        '500':
          description: 服务器错误

  /auth/logout:
    post:
      summary: 用户登出
      tags:
        - 认证
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  description: 刷新令牌
      responses:
        '200':
          description: 登出成功
        '401':
          description: 未经授权
        '500':
          description: 服务器错误

  /auth/forgot-password:
    post:
      summary: 请求密码重置
      tags:
        - 认证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  description: 用户邮箱
      responses:
        '200':
          description: 密码重置邮件已发送
        '404':
          description: 用户未找到
        '500':
          description: 服务器错误

  /auth/reset-password:
    post:
      summary: 重置密码
      tags:
        - 认证
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  description: 重置令牌
                newPassword:
                  type: string
                  description: 新密码
      responses:
        '200':
          description: 密码重置成功
        '400':
          description: 无效或过期的令牌
        '500':
          description: 服务器错误

  /auth/token-times:
    get:
      summary: 获取令牌过期时间
      tags:
        - 认证
      responses:
        '200':
          description: 成功获取令牌时间
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessTokenExpiryTime:
                    type: string
                  refreshTokenExpiryTime:
                    type: string
        '500':
          description: 服务器错误

  /auth/update-token-times:
    post:
      summary: 更新令牌过期时间
      tags:
        - 认证
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accessTokenTime
                - refreshTokenTime
              properties:
                accessTokenTime:
                  type: string
                  description: 访问令牌有效期
                refreshTokenTime:
                  type: string
                  description: 刷新令牌有效期
      responses:
        '200':
          description: 令牌时间更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '400':
          description: 验证错误
        '401':
          description: 未经授权
        '500':
          description: 服务器错误

  /user/profile:
    get:
      summary: 获取用户资料
      tags:
        - 用户管理
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 成功获取用户资料
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
        '401':
          description: 未经授权
        '404':
          description: 用户未找到
        '500':
          description: 服务器错误
    put:
      summary: 更新用户资料
      tags:
        - 用户管理
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 新用户名
                email:
                  type: string
                  description: 新邮箱
      responses:
        '200':
          description: 用户资料更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
        '400':
          description: 验证错误
        '401':
          description: 未经授权
        '500':
          description: 服务器错误

  /user/change-password:
    post:
      summary: 修改用户密码
      tags:
        - 用户管理
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - oldPassword
                - newPassword
              properties:
                oldPassword:
                  type: string
                  description: 旧密码
                newPassword:
                  type: string
                  description: 新密码
      responses:
        '200':
          description: 密码修改成功
        '400':
          description: 验证错误或旧密码不正确
        '401':
          description: 未经授权
        '500':
          description: 服务器错误

  /user/account:
    delete:
      summary: 删除用户账户
      tags:
        - 用户管理
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 账户删除成功
        '401':
          description: 未经授权
        '500':
          description: 服务器错误

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT